name: EasyServerManager
author: PsychoGamer_95
version: 0.1
website: https://www.fukanoherde.de
main: de.psychogamer_95.easyservermanager.Main
commands:
  gamemode:
    aliases:
      - gm
    description:
  zeit:
    description:
  ban:
    aliases:
      - b
    description:
  tempban:
    aliases:
      - tb
    description: